"""add tool_calls and tool_call_id to messages

Revision ID: 43a2b107dae2
Revises: f468c671cbff
Create Date: 2026-07-26 16:16:05.967210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43a2b107dae2'
down_revision: Union[str, Sequence[str], None] = 'f468c671cbff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_calls', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('tool_call_id', sa.String(length=100), nullable=True))
    op.alter_column('messages', 'role',
               existing_type=mysql.ENUM('user', 'assistant', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.create_index(op.f('ix_messages_role'), 'messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_role'), table_name='messages')
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('user', 'assistant', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('messages', 'tool_call_id')
    op.drop_column('messages', 'tool_calls')
    # ### end Alembic commands ###
