"""add llm_usage table

Revision ID: c8eba06d0ef1
Revises: 2e4a1b8c9d0f
Create Date: 2026-07-28 15:59:36.195273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8eba06d0ef1'
down_revision: Union[str, Sequence[str], None] = '2e4a1b8c9d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('req_id', sa.String(length=32), nullable=False, comment='请求关联 ID'),
    sa.Column('session_id', sa.Integer(), nullable=True, comment='会话 ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户 ID'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='总 token 数'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='输入 token 数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='输出 token 数'),
    sa.Column('cached_tokens', sa.Integer(), nullable=True, comment='缓存命中 token 数'),
    sa.Column('cache_rate', sa.Integer(), nullable=True, comment='缓存命中率（百分比，0~100）'),
    sa.Column('turns', sa.Integer(), nullable=True, comment='LLM 调用轮次'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_req_id'), 'llm_usage', ['req_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_usage_req_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
