"""avatar_column_to_text

Revision ID: f468c671cbff
Revises: 88faa96a7d35
Create Date: 2026-07-24 11:16:34.499948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f468c671cbff'
down_revision: Union[str, Sequence[str], None] = '88faa96a7d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256),
               existing_nullable=False)
    # ### end Alembic commands ###
